language: cpp
compiler: clang
before_script:
- sudo apt-get update
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list.d/xenial.list
- sudo apt-get update
- sudo apt install libspdlog-dev doxygen -y

script:
- cmake .
- cmake --build .
- cmake --build . --target package
- git clone https://github.com/vikorzel/vikorzel.github.io.git html
- doxygen Doxyfile

deploy:
  provider: script
  skip_cleanup: true
  script:
- curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uvikorzel:$BINTRAY_API_KEY "https://api.bintray.com/content/otushomeworks/otushw/homework/$TRAVIS_BUILD_NUMBER/otusprintip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty,bionic;deb_component=main;deb_architecture=amd64;publish=1"
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: html
  on:
    branch: master